name: promart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_check: ^1.0.5
  bloc: ^8.0.2
  built_collection: ^5.1.1
  cached_network_image: ^3.2.0
  carousel_slider: 4.0.0
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_form_bloc: ^0.29.3
  flutter_screenutil: ^5.2.0
  flutter_shimmer: ^2.1.2
  font_awesome_flutter: ^9.2.0
  formz: ^0.4.1
  freezed_annotation: ^1.1.0
  getwidget: ^2.0.4
  go_router: ^3.0.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.1
  hive: ^2.0.5
  hydrated_bloc: ^8.0.0
  logger: ^1.1.0
  pedantic: ^1.11.1
  responsive_framework: ^0.1.5
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11
  sizer: ^2.0.15
  sqflite: ^2.0.1

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: ^6.1.4
  lint: ^1.8.2
  very_good_analysis: ^2.4.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
