name: promart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  errors:
    git:
      url: git://github.com/NoScopeDevs/errors
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.29.3
  font_awesome_flutter: ^9.2.0
  formz: ^0.4.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.1
  hive: ^2.0.5
  logger: ^1.1.0
  shared_preferences: ^2.0.11
  sqflite: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
