name: promart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.0.2
  built_collection: ^5.1.1
  cached_network_image: ^3.2.0
  carousel_slider: 4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_screenutil: ^5.2.0
  flutter_shimmer: ^2.1.2
  formz: ^0.4.1
  google_sign_in: ^5.2.1
  hydrated_bloc: ^8.0.0
  logger: ^1.1.0
  responsive_framework: ^0.1.5
  promart_api:
    path: packages/promart
  dio_network_exceptions:
    path: packages/dio_network_exceptions
  firebase_exceptions:
    path: packages/firebase_exceptions
  animated_check: ^1.0.5
  getwidget: ^3.0.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
