name: promart
description: Dart package to manage {Feature} data and domain layers.
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_exceptions:
    path: ../firebase_exceptions
  dio_network_exceptions:
    path: ../dio_network_exceptions
  logger: ^1.1.0
  firebase_auth: ^0.15.1+1
  google_sign_in: ^4.0.16
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0